sudo: required
services:
  - docker

before_install: 
  - docker build -t futumans/docker-nginx -f Dockerfile.dev .

script: 
  - docker run  futumans/docker-nginx  

language: minimal

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-nginx"
  env: "Dockernginx-env"
  bucket_name: "elasticbeanstalk-us-east-1:652213986584"
  bucket_path: "docker-nginx"

on:
  branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: "$AWS_SECRET_KEY"
edge: true